name: spot_hot
description: senior design

version: 1.0.0+1

environment:
  sdk: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3
  google_maps_flutter: ^1.0.2
  geolocator: ^6.0.0+4
  image_picker: ^0.6.7+12
  flushbar: ^1.10.4
  permission_handler: ^5.0.1+1
  firebase_image: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
